# .github/workflows/cypress.yml
name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Install Cypress binary
        run: npx cypress install

      - name: Build Vite project
        run: npm run build

      - name: Start server and run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_baseUrl: http://localhost:4173
        with:
          start: npm run preview -- --host 0.0.0.0
          wait-on: 'http://localhost:4173'
          wait-on-timeout: 180
          browser: chrome
          record: false
          install: false

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Debug FTP Connection
        if: success()
        run: |
          echo "Testing FTP server connection..."
          ping -c 3 ${{ secrets.FTP_SERVER }} || echo "Ping failed"
          nc -zv ${{ secrets.FTP_SERVER }} 21 || echo "FTP port 21 not accessible"
          nc -zv ${{ secrets.FTP_SERVER }} 22 || echo "SSH/SFTP port 22 not accessible"

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        if: success()
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./public_html/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**